# Generated by Django 2.2.13 on 2022-06-21 11:54

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeptideStructureData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(default='NULL', storage=django.core.files.storage.FileSystemStorage(location='/home/thajan/Desktop/projects/mobilenet/leaf_dicease_classiffication'), upload_to='media/modelData/upload/')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
